name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-version: ['5.0.x']
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./ScriperSol
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./ScriperSol
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./ScriperSol
