name: Unit Tests 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    name: Build & Unit Test
    strategy:
      matrix: 
        dotnet-version: ['5.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./ScriperSol
      - name: Build Scriper
        run: msbuild /t:Rebuild
        working-directory: .\ScriperSol\Scriper.UnitTests
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
        working-directory: .\ScriperSol\Scriper.UnitTests
