name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-version: ['5.0.x']
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./ScriperSol
      - name: Build Scriper
        # run: dotnet build --configuration Release --no-restore
        run: start "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ".\Scriper.UnitTests.csproj"
        working-directory: .\ScriperSol\Scriper.UnitTests
      - name: Test
        run: dotnet test Scriper.UnitTests.csproj .\ --no-build --verbosity normal
        working-directory: .\ScriperSol\Scriper.UnitTests
